### ISSUE TITLE
Updated release

### ISSUE THREAD

**Issue by LandonSchropp** [lodash/babel-plugin-lodash#210]
It would be awesome to see a release of this package. I'm chomping at the bit to use the chain syntax merged in #176. 😃

**Comment by panuchka** [comment]
Eagerly waiting for the npm package too! Why isn't it published yet? 🤔

**Comment by panuchka** [comment]
Could we have any ETA on the 3.3.3. release? In package.json it says 3.3.3-pre, so is something still unfinished or untested? If so, could we have the plugin published with the pre/next tag so it would at least be available right now?

Would really need this asap or at least a time estimate, since have to make decisions on ditching&rewriting all the chains or to use this plugin...

**Comment by sanniassin** [comment]
I've built current `master` branch as a temporary workaround until `3.3.3` is released.

`npm install --save-dev https://github.com/sanniassin/babel-plugin-lodash/archive/3.3.3-pre.tar.gz`

**Comment by hipstersmoothie** [comment]
@jdalton This is honestly ridiculous. The initial PR was opened over a year ago. At least release an alpha so we can test it for you. It's getting awfully close to 2019 in "babel-plugin-lodash"-time.

**Comment by hipstersmoothie** [comment]
The issue was initially opened Jul 13, 2016. So we are even closing in on 2 years of this being an issue.

**Comment by jdalton** [comment]
Hi @hipstersmoothie!

I'm glad you're excited about the PR. I'm not carrying over chaining syntax into Lodash v5 so I've been dragging my feet on this specific enhancement. I think it's better that I just revert the addition and close this issue. Thanks!
